Return public users activities, starting from given time (Optional)
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
consumes:
  "application/json"
tags:
  - name: "Socializing"
parameters:
  - in: header
    name: Authorization
    description: "Send like this: Bearer [TOKEN]"
    type: string
    required: true
  - name: "page"
    in: "query"
    description: "Which page do want to get"
    required: false
    type: "integer"
  - name: "page_size"
    in: "query"
    description: "the number of links in each page"
    required: false
    type: "integer"
  - name: body
    in: body
    required: true
    schema:
      properties:
        date_from:
          type: string
          description: "Starting date with this format: YYYY-MM-DD hh:mm `Optional`"
          example: "2020-12-05 19:12"

responses:
  200:
    description: "Return activities list"
    schema:
        type: array
        items:
          type: object
          properties:
            user_id:
              type: int
            username:
              type: string
            total_links_added_after_given_time:
              type: int
              description: Number of total links that are added from given time
            last_link_added_date:
              type: string
        description: "Link related categories"
        example:
            [
              {"user_id": 8, "username": "test1@gmail.com", "total_links_added_after_given_time": 11, "last_link_added_date": "2020-12-05 19:15"},
              {"user_id": 31, "username": "test2@yahoo.com", "total_links_added_after_given_time": 8, "last_link_added_date": "2020-12-11 05:37"}
            ]
  400:
    description: "Input does not match format 'YYYY-MM-DD hh:mm' OR Requested page size is larger than our max limit!"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Input does not match format 'YYYY-MM-DD hh:mm' OR Requested page size is larger than our max limit!"
      example:
        msg: "Input does not match format 'YYYY-MM-DD hh:mm'"
  404:
    description: Didn't found any activity from that time
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Didn't found any activity from that time
      example:
        msg: Didn't found any activity from that time
