Get categories for owner of current token
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags:
  - name: "Categories"
parameters:
  - name: Authorization
    in: header
    description: "Send like this: Bearer [TOKEN]"
    type: string
    required: true
  - name: "id"
    in: "path"
    description: "Category id to get"
    required: false
    type: "integer"
example:
  Authorization: "Bearer eyJ0eXAiOi...."
  id: 1
responses:
  200:
    description: "Return categories"
    schema:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        description: "Link related categories"
        example:
            categories: [
                {"id": 1, "name": "programming"},
                {"id": 5, "name": "searching"},
                {"id": 11, "name": "Q and A"}
            ]
  404:
    description: "Category ID not found"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Category not found!
      example:
        msg: Category not found!