Get bookmarks for owner of current token that contain special key word
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags:
  - name: "Links"
parameters:
  - name: Authorization
    in: header
    description: "Send like this: Bearer [TOKEN]"
    type: string
    required: true
  - name: "pattern"
    in: "path"
    description: "Word to contain"
    required: true
    type: string
  - name: "page"
    in: "query"
    description: "Which page do want to get"
    required: false
    type: "integer"
  - name: "page_size"
    in: "query"
    description: "the number of links in each page"
    required: false
    type: "integer"
example:
  Authorization: "Bearer eyJ0eXAiOi...."
responses:
  200:
    description: "Return bookmarks that contain special key word in their URL"
    schema:
      type: object
      properties:
        search:
          type: object
          properties:
            pattern:
              type: string
            links:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
      example:
        search:
          pattern: vim
          links: [
            {id: 4, url: "https://this-has-vim.com"},
            {id: 7, url: "http://vim.org"},
            {id: 11, url: "https://vim-love-vim.com"}
          ]
  400:
    description: "Requested page size is larger than our max limit!"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Requested page size is larger than our max limit!"
      example:
        msg: "Requested page size is larger than our max limit!"  
  404:
    description: "Pattern not found"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Pattern not found!
      example:
        msg: Pattern not found!