Get bookmarks for owner of current token
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
parameters:
  - in: header
    name: Authorization
    description: "Send like this: Bearer [TOKEN]"
    schema:
      type: string
      format: uuid
    required: true
responses:
  200:
    description: "Return bookmarks"
    schema:
      type: object
      properties:
        address_name:
          type: array
          items:
            type: string
          description: "Bookmarked links"
      example:
        address_name: ["www.stackoverflow.com", "www.geeksforgeeks.com"]