Get bookmarks for owner of current token
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
parameters:
  - in: header
    name: Authorization
    description: "Send like this: Bearer [TOKEN]"
    schema:
      type: string
      format: uuid
    required: true
responses:
  200:
    description: "Return bookmarks Id"
    schema:
      type: object
      properties:
        bookmarked_links_id:
          type: array
          items:
            type: int
          description: "Bookmarked links id"
      example:
        bookmarked_links_id: [1, 5]