Delete bookmark for owner of current token by Id
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
consumes:
  "application/json"
tags:
  - name: "Links"
parameters:
  - name: Authorization
    in: header
    description: "Send like this: Bearer [TOKEN]"
    type: string
    required: true
  - name: "id"
    in: "path"
    description: "Link id to delete"
    required: true
    type: "integer"
responses:
  200:
    description: "Bookmarked link Deleted"
    schema:
      type: object
      properties:
        link_id:
          type: int
          description: "Link Id"
        msg:
          type: string
          description: "Link removed successfully."
      example:
        link_id: "1"
        msg: "Link removed successfully."
  403:
    description: "You don't have permission to remove this link"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: You don't have permission to remove this link
      example:
        msg: You don't have permission to remove this link
  404:
    description: "Link doesn't found"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Link doesn't exists!
      example:
        msg: Link doesn't exists!