Delete bookmark for owner of current token
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
consumes:
  "application/json"
parameters:
  - in: header
    name: Authorization
    description: "Send like this: Bearer [TOKEN]"
    schema:
      type: string
      format: uuid
    required: true
  - name: body
    in: body
    required: true
    schema:
      required:
        - link_id
      properties:
        link_id:
          type: int
          description: "Link Id"
      example:
        link_id: "1"
responses:
  200:
    description: "Bookmark Deleted"
    schema:
      type: object
      properties:
        link_id:
          type: int
          description: "Link Id"
        msg:
          type: string
          description: "Link removed successfully."
      example:
        link_id: "1"
        msg: "Link removed successfully."
  403:
    description: "You don't have permission to remove this link"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: You don't have permission to remove this link
      example:
        msg: You don't have permission to remove this link
  406:
    description: "Link doesn't exists!"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Link doesn't exists!
      example:
        msg: Link doesn't exists!