Get bookmarks for owner of current token by special Category ID
---
openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags:
  - name: "Links"
parameters:
  - name: Authorization
    in: header
    description: "Send like this: Bearer [TOKEN]"
    type: string
    required: true
  - name: "id"
    in: "path"
    description: "Category id to get"
    required: true
    type: "integer"
  - name: "page"
    in: "query"
    description: "Which page do want to get"
    required: false
    type: "integer"
  - name: "page_size"
    in: "query"
    description: "the number of links in each page"
    required: false
    type: "integer"
example:
  Authorization: "Bearer eyJ0eXAiOi...."
  id: 1
responses:
  200:
    description: "Return bookmarks related to special category"
    schema:
      type: object
      properties:
        category:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            links:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
      example:
        category:
          id: 2
          name: programming
          links: [
            {id: 4, url: "https://stackoverflow.com"},
            {id: 7, url: "http://geekforgeeks.com"},
            {id: 11, url: "http://developer.com"}
          ]
  400:
    description: "Requested page size is larger than our max limit!"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Requested page size is larger than our max limit!
      example:
        msg: Requested page size is larger than our max limit!
  404:
    description: "Category ID not found"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: Category ID not found!
      example:
        msg: Category ID not found!