Step 1) Send random 8 digit code to user's Email and return a hash
---
openapi: 3.0.0
consumes:
  "application/json"
tags:
  - name: "Forget Password"
parameters:
  - name: body
    in: body
    required: true
    schema:
      required:
        - username
      properties:
        username:
          type: string
          description: "Username that requested password recovery"
          example: "test@somewhere.com"
        
responses:
  200:
    description: "Random number sent to user's email and a hashed key is returned"
    schema:
      type: object
      properties:
        hashed_data:
          type: string
          description: "A hashed string containing user's ID and valid 8 digit code"
      example:
        hashed_data: "eyJhb..."
  404:
    description: "User not found"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Username not found"
      example:
        msg: "Username not found"
