Step 3) Reset user's password
---
openapi: 3.0.0
consumes:
  "application/json"
tags:
  - name: "Forget Password"
parameters:
  - name: body
    in: body
    required: true
    schema:
      required:
        - reset_password_token
        - new_password
      properties:
        reset_password_token:
          type: string
          description: "Token for resetting password that is obtained from prevoius call to /verify_code"
          example: "eyJhb..."
        new_password:
          type: string
          description: "User's new password"
          example: "new_test_Pass00rd"
responses:
  200:
    description: "Password reseted successfully."
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Password reseted successfully."
      example:
        msg: "Password reseted successfully."
  401:
    description: "Token expired!"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Token expired!"
      example:
        msg: "Token expired!"
  401:
    description: "Token invalid!"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Token invalid!"
      example:
        msg: "Token invalid!"
  500:
    description: "Failed due to server error"
    schema:
      type: object
      properties:
        msg:
          type: string
          description: "Failed due to server error"
      example:
        msg: "Failed due to server error"