version: "2"
services:
    app:
        container_name: restfulness
        build: ./
        links:
            - db
        ports:
            - "5000:5000"

    db:
        container_name: mysql
        image: mysql:8.0
        ports:
            - "32000:3306" # I have mysql-server installed on my machine, so using other port instead of 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./:/docker-entrypoint-initdb.d/:ro